### ISSUE TITLE
Vegreferanse klassen håndterer ikke strekningsreferanser.

### ISSUE THREAD

**Issue by Acurus** [Acurus/pnvdb#1]
```
obj = nvdb.objekt(67,86520350)
for i in obj.vegreferanser:
    print(vegref.detaljert)

https://www.vegvesen.no/nvdb/api/v2/veg?vegreferanse=0300+Rv150+hp85+m12064-12178

Traceback (most recent call last):
  File "<pyshell#10>", line 2, in <module>
    print(i.detaljert)
  File "C:\Python27\ArcGISx6410.4\lib\site-packages\pnvdb\les.py", line 326, in detaljert
    self.data = self._fetch_data('veg', payload={'vegreferanse':self.vegreferanse})
  File "C:\Python27\ArcGISx6410.4\lib\site-packages\pnvdb\les.py", line 18, in _fetch_data
    data = self._check_response(resp, format)
  File "C:\Python27\ArcGISx6410.4\lib\site-packages\pnvdb\les.py", line 32, in _check_response
    raise ApiError(read_api_error(resp))
ApiError

```

**Comment by Acurus** [comment]
Rewrote the class, to fix the issue.
